spring.application.name=e-rank-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:[Siyabonga@13]@db.tptgoxvxvwaonodcvgwx.supabase.co:5432/postgres
spring.datasource.username=eRank_Database
spring.datasource.password=Siyabonga@25
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

jwt.secret=eRankSuperSecretKeyForJWTAuthenticationPMPSolutions2024
jwt.expiration=300000

spring.web.cors.allowed-origins=http://localhost:5173